### ISSUE TITLE
Support some quick preset date ranges 

### ISSUE THREAD

**Issue by andybak** [silentsokolov/django-admin-rangefilter#1]
Really pleased to find this as I was considering writing something similar.

It's great for 'power users' but misses some of the simplicity of the standard date filter. I wonder if the addition of some presets would give the best of both worlds? i.e. 'today', 'this week' etc.

I might work on it myself if I get time and I'll plan for a PR instead of a custom fork if you think it would be a useful addition.

**Comment by silentsokolov** [comment]
A good idea. Need to think how to implement it. Backward compatibility with AdminDateWidget imposes restrictions ...

**Comment by imbolc** [comment]
Hey, guys, is here any news?

**Comment by silentsokolov** [comment]
No

**Comment by macolo** [comment]
Something like combining this module with the DateTimeFilter works, however the url parameters get mingled, like for example: http://127.0.0.1:8000/admin/work/workentry/?date__lt=2018-07-03&date__gte=2018-05-01&date__lte=2018-05-02 

Is there an easy way to prevent this from happening?

```
    list_filter = (
        ('date', DateTimeFilter),
        ('date', DateRangeFilter),
```

**Comment by silentsokolov** [comment]
After version `0.4.0`, your might use `list_filter = ('date', DateFieldListFilter), ('date', DateRangeFilter)`
