### ISSUE TITLE
DateRangeFilter malfunctions on mutiple fields

### ISSUE THREAD

**Issue by Spacehug** [silentsokolov/django-admin-rangefilter#10]
I have list_filter as such:
list_filter = ('is_active', ('last_email_date', DateRangeFilter), ('date_joined', DateRangeFilter))

Only the one with last_email_date is working, the other is not. If I swap them, the one that goes first will work, and the other will not.

**Comment by silentsokolov** [comment]
Say you django and rangefilter version

**Comment by Spacehug** [comment]
Django 1.10, rangefilter 0.3.0

**Comment by silentsokolov** [comment]
I could not reproduce the error. [Recreated](https://user-images.githubusercontent.com/398939/31494197-ed3fec66-af5a-11e7-9813-5ed640af35da.jpg) your situation, but filter working, maybe you set incorrect type: DateRangeFilter not working with DateField and etc)
