### ISSUE TITLE
Select a range by two fields using one filter

### ISSUE THREAD

**Issue by quant12345** [silentsokolov/django-admin-rangefilter#109]
There are two model fields start and end (date) for each record. I need to select a range. Is it possible to do this using one filter?

**Comment by silentsokolov** [comment]
No. I think in your case, there is no need for a separate widget; just use the standard functionality.

**Comment by quant12345** [comment]
I just think it’s unnecessary to specify the range for start and end separately. In theory, you need to filter from the minimum start to the maximum end, and therefore why two filters?

 'no need for a separate widget' , what do you mean by this?

**Comment by silentsokolov** [comment]
>  In theory, you need to filter from the minimum start to the maximum end
I see... 
In any case, this library doesn't provide such functionality ((
