### ISSUE TITLE
NumericRangeFilter clears all other filters

### ISSUE THREAD

**Issue by dibusan** [silentsokolov/django-admin-rangefilter#110]
* I have a list of simple filters built with `django_filters` app. 
* I would like to introduce a numeric range filter using `rangefilter`. 
* I add the range filter and it works as expected, ONLY when it is the only filter applied. If there are other filters, it will clear them, so I cannot have multiple filters.

`Django: 3.2.22`
`django-admin-rangefilter: 0.9.0`

```
# Note that both NumericRangeFilter and DateRangeFilter show the same behavior.
class MyAdminPage():
  list_filters = (
    "CustomMultiIdSearchFilter",
    "CustomTaxIdFilter",
    ("amount", NumericRangeFilter),
    ("end", DateRangeFilter),
  )
```

```
INSTALLED_APPS = [
  ...
  "django_filters",
  "rangefilter",
  "csp",
  ...
]
```

**Comment by silentsokolov** [comment]
Could you give more information?

I checked base cases and the query string generated correctly

Example:
```python
list_filter = [
    (
        "created_at",
        DateRangeFilterBuilder(
            title="TEST TEST",
            default_start=datetime(2020, 1, 1),
            default_end=datetime(2030, 1, 1),
        ),
    ),
    ("updated_at", DateRangeQuickSelectListFilter),
    ("updated_at", DateTimeRangeFilter),
    ("int_v", NumericRangeFilter),
    "int_v",
]
```

**Comment by dibusan** [comment]
1. Search on a simple string filter. GOOD

<img width="1383" alt="Screenshot 2023-11-27 at 12 59 02 PM" src="https://github.com/silentsokolov/django-admin-rangefilter/assets/44810593/8b38923c-9851-4c90-aff5-bd5945cdf7c5">

1. Search on a range filter. BAD. The search filter clears up. Same thing happens with any other filter, including if the only 2 filters are both range filters (only 1 range filter will apply)

<img width="1413" alt="Screenshot 2023-11-27 at 1 02 26 PM" src="https://github.com/silentsokolov/django-admin-rangefilter/assets/44810593/73126760-ae5f-408b-a31e-255a793e3570">

1. Search on a simple string filter with the range filter applied. GOOD, both filters apply

<img width="1414" alt="Screenshot 2023-11-27 at 1 04 25 PM" src="https://github.com/silentsokolov/django-admin-rangefilter/assets/44810593/820b2e23-112f-4753-9d0c-e940173e0d4c">

CSP error that I cannot track. It only shows briefly when I click the range filter search and then disappears once the filer is applied (page reloads). I can say confidently this CSP error is not coming from any of our templates. Perhaps the solution in a specific CSP config ?

![Screenshot 2023-11-27 at 1 07 17 PM](https://github.com/silentsokolov/django-admin-rangefilter/assets/44810593/b36da7b3-9cb6-4fc9-9703-8c8955bd7f65)

@silentsokolov

**Comment by dibusan** [comment]
I had seen [this](https://github.com/silentsokolov/django-admin-rangefilter) in the README but didn't understand it before. Where exactly should this setting be configured ? I add it to `settings.py` at the first level but has no effect.

![Screenshot 2023-11-27 at 1 24 35 PM](https://github.com/silentsokolov/django-admin-rangefilter/assets/44810593/ce967de8-7519-4709-a21a-4aa14165675c)

**Comment by silentsokolov** [comment]
I knew it all along. 

1. `django-admin-rangefilter` supports **only** default admin UI.
2. For CSP need setup middleware / context_processors, please [read docs](https://django-csp.readthedocs.io/en/latest/)

**Comment by dibusan** [comment]
@silentsokolov Even with CSP working (that means `ADMIN_RANGEFILTER_NONCE_ENABLED = True` in `settings.py`), the NumericRangeFilter does not load CSP in `v 0.9.0`:

- I have confirmed that `NumericRangeFilter` (`rangefilter/numeric_filter.html`) does not make an attempt to load the CSP
- DateRangeFilter does work as expected. It does load the CSP.
- There is an obvious difference in the `get_template` for these 2 Classes, see screenshots attached
- The package includes a `date_filter_csp.html` but it does not include a `numeric_filter_csp.html`, see screenshot attached

![Screenshot 2023-11-30 at 12 06 31 PM](https://github.com/silentsokolov/django-admin-rangefilter/assets/44810593/266c704f-e47a-40f5-afd6-fa70b745af78)
![Screenshot 2023-11-30 at 12 09 25 PM](https://github.com/silentsokolov/django-admin-rangefilter/assets/44810593/9f82773f-b463-47b0-a919-09d056c7bf83)
![Screenshot 2023-11-30 at 12 14 54 PM](https://github.com/silentsokolov/django-admin-rangefilter/assets/44810593/46a77ca9-3e0e-4229-a1ca-46d6c80fe86f)

**Comment by silentsokolov** [comment]
Thx, fix
