### ISSUE TITLE
DateRangeQuickSelectListFilter does not show quick select list

### ISSUE THREAD

**Issue by daphtdazz** [silentsokolov/django-admin-rangefilter#118]
It just shows the date range picker.

The problem seems to be that `DateRangeQuickSelectListFilter` overrides `get_template()` but `DateRangeFilter` defines:

```py
    def get_template(self):
        ...

    template = property(get_template)
```

So `DateRangeQuickSelectListFilter().template` calls `DateRangeFilter.get_template()` instead of `DateRangeQuickSelectListFilter.get_template()`

I'm on django 4.2.13 don't know if maybe something changed in django to affect this (maybe it used to use `get_template()`..?).

If I get a sec I will push a fix but I'm patching it for myself locally like this:

```py
from rangefilter.filters import DateRangeQuickSelectListFilter
DateRangeQuickSelectListFilter.template = property(DateRangeQuickSelectListFilter.get_template)
```

**Comment by silentsokolov** [comment]
Fixed, thx!
