### ISSUE TITLE
My default search button doesn't work.

### ISSUE THREAD

**Issue by AenishShrestha** [silentsokolov/django-admin-rangefilter#122]
My code looks like this when after i have installed django-admin-rangefilter 
    list_filter = ["customer", "status", "delivery_boy", "payment_method", "delivery_location", "delivery_location_option", ("order_creation_date",DateRangeFilter), ('delivery_date',DateRangeFilter)]

    list_display = ["order_id", "status", "customer", "delivery_boy", "delivery_boy_contact", "delivery_location", "delivery_charge", "order_creation_date", "delivery_date", "payment_method", "display_order_products"]

But when i use search button of default admin panel it wont work. 

![image](https://github.com/silentsokolov/django-admin-rangefilter/assets/84612270/2821fe36-a475-4138-aa42-5c33d315037a)

**Comment by silentsokolov** [comment]
django-admin-rangefilter supports **only** default django admin UI
