### ISSUE TITLE
Error when i search it

### ISSUE THREAD

**Issue by joelalves** [silentsokolov/django-admin-rangefilter#13]
python 3.5
django 1.11.6
django-admin-rangefilter 0.3.0

Url examplpe = '/voucher/?&date_order__gte=2018-01-01&date_order__lte=2018-01-10'

Problem:

'LocalTimezone' object has no attribute 'localize'

View more details [here](http://prntscr.com/i2x294)

**Comment by silentsokolov** [comment]
@joelalves Tell me what timezone settings you use

**Comment by joelalves** [comment]
https://github.com/joelalves/django_erp/blob/master/django_erp/settings/base.py

**Comment by silentsokolov** [comment]
I could not reproduce the error.

1) What version `pytz` you using?
2) You using default method `get_timezone`?

**Comment by joelalves** [comment]
I am using pytz (2017.3)
2. Where?
The field that use for filter ([see here](https://github.com/joelalves/django_erp/blob/master/erp/models.py#L58))

**Comment by silentsokolov** [comment]
Hm ... you sure?

You say that use django 1.11.6, but `django.utils.timezone.LocalTimezone` [remove](https://docs.djangoproject.com/en/1.10/_modules/django/utils/timezone/) in [1.11](https://docs.djangoproject.com/en/1.11/_modules/django/utils/timezone/).

**Comment by joelalves** [comment]
![pip_list](https://user-images.githubusercontent.com/3008598/35280587-8acbe7b2-0048-11e8-8cb4-72d8830b64ef.PNG)

Yes, i am sure...You see in image

**Comment by silentsokolov** [comment]
This is not the environment in which the error occurred. On [screen](https://github.com/silentsokolov/django-admin-rangefilter/issues/13#issue-290147259) MacOS

**Comment by joelalves** [comment]
it´s true, but the same environment

**Comment by silentsokolov** [comment]
Okay, reproduce the error and send the [complete log](https://prnt.sc/i4g89h)

**Comment by joelalves** [comment]
ok, tonight i will send the complete log

**Comment by joelalves** [comment]
It's working after de commit.
Thanks You

**Comment by silentsokolov** [comment]
Of course, this change makes `pytz` is optional. You do not have `pytz`, because up to the version django 1.11.X, it is not necessary. You have to accept when you make mistakes.

Thx for issues.
