### ISSUE TITLE
Reset button appears wrong with Grappelli

### ISSUE THREAD

**Issue by shaib** [silentsokolov/django-admin-rangefilter#14]
Hi,

I know that Grappelli isn't officially supported, but I wanted to share that under Django 1.11 with Grappelli  2.10.1, the date-range filter is working fine -- except that the Reset button's look is a bit off. We solved this by copying the `date_filter.html` template, and commenting out the styling for it (the `.button, input[type=reset]` block).
It may or may not be desirable to solve this in a more systematic way.

**Comment by silentsokolov** [comment]
Can you make PR? Change the code that the [template selection](https://github.com/silentsokolov/django-admin-rangefilter/blob/master/rangefilter/filter.py#L90). I'll be happy if we have support Grappelli.

Anyway thanks!

**Comment by shaib** [comment]
I hope to be able to make a PR some time soon, but I don't know how soon
