### ISSUE TITLE
Pip install fails in Python 2.7  for version 0.3.4

### ISSUE THREAD

**Issue by thulasi-ram** [silentsokolov/django-admin-rangefilter#15]
Changes made in commit is preventing installation of version 0.3.4 in Python 2.7:
https://github.com/silentsokolov/django-admin-rangefilter/commit/718ed5ca1454139f672a52a2263ac2f185a8258d

```
def read_md(f):
    return open(f, 'r', encoding='utf-8').read()
```

> pip install django-admin-rangefilter fails with TypeError: 'encoding' is an invalid keyword argument for this function

pip install django-admin-rangefilter==0.3.3 doesn't.

<img width="1162" alt="screen shot 2018-04-16 at 2 43 19 pm" src="https://user-images.githubusercontent.com/5107093/38800313-92ccc0bc-4184-11e8-9856-38a7ca23802a.png">

**Comment by silentsokolov** [comment]
Thx, fix
