### ISSUE TITLE
Do not display calendar controls

### ISSUE THREAD

**Issue by qulc** [silentsokolov/django-admin-rangefilter#20]
Python3.7  
Django 2.1

![image](https://user-images.githubusercontent.com/4693764/45952006-341fc900-c038-11e8-9e3a-eb8ae9b68af6.png)

I find the reason is `admin/js/calendar.js` and `admin/js/admin/DateTimeShortcuts.js` not loading

try change always loading js,  but the just working disable cache mode!

```python
class DatetimeRangeFilter(DateTimeRangeFilter):
    def get_form(self, request):
        form_class = super().get_form(request)
        form_class.js = super().get_js()
        return form_class
```

**Comment by silentsokolov** [comment]
We do not officially support 2.1 version, you tested with 2.0?

**Comment by silentsokolov** [comment]
I tested without cache
- 3.6/2.0
- 3.7/2.0
- 3.6/2.1
- 3.7/2.0

Everything is working

@qulc please, check serve you static and check calendar controls on edit page (js work on edit page?), if the error is not resolved reopen issue

**Comment by silentsokolov** [comment]
May be this is somewhat related to #21

**Comment by VictorIsra** [comment]
same problem here...no solutions at all
