### ISSUE TITLE
RemovedInDjango30Warning: {% load admin_static %} is deprecated

### ISSUE THREAD

**Issue by daniel-ruiz** [silentsokolov/django-admin-rangefilter#26]
Hello! 👋 

I wanted to thank you for building this package beforehand. It saved me and my teammates a whole deal of work!

We are using the latest version of `django-admin-rangefilter` ([v0.3.10](https://github.com/silentsokolov/django-admin-rangefilter/releases/tag/v0.3.10)) in our Django project. Recently, after upgrading Django to version [2.1](https://docs.djangoproject.com/en/2.1/releases/2.1/) we started seeing the following deprecation warning in our logs:

```
RemovedInDjango30Warning: {% load admin_static %} is deprecated in favor of {% load static %}
```

I've found out there are several references to `admin_static` in `django-admin-rangefilter` that are likely the source of these warnings (see [here](https://github.com/silentsokolov/django-admin-rangefilter/search?q=load+admin_static&unscoped_q=load+admin_static)).

It would be amazing that this warning will be suppressed. Do not hesitate to contact me if you need some help with the fix 😄

**Comment by silentsokolov** [comment]
Hello!

Thanks for issue and PR but there is a problem: we support Django 1.8+. In version `1.8` `admin_static` is not deprecated.

**Comment by silentsokolov** [comment]
[1.8.x](https://github.com/django/django/blob/stable/1.8.x/django/contrib/admin/templatetags/admin_static.py) is normal, package uses template `rangefilter/date_filter_1_8.html`
[1.9.x](https://github.com/django/django/blob/stable/1.9.x/django/contrib/admin/templatetags/admin_static.py) is normal, package uses template `rangefilter/date_filter.html`
[2.0.x](https://github.com/django/django/blob/stable/2.0.x/django/contrib/admin/templatetags/admin_static.py) is deprecated, package uses template `rangefilter/date_filter.html`

I do not want to create a template for version 1.9 :(

I have no solution yet. You can override the template `rangefilter/date_filter.html` in your project if this problem bothers you.

**Comment by silentsokolov** [comment]
Best solution create custom [template tag](https://docs.djangoproject.com/en/2.1/howto/custom-template-tags/), which depending on the version, will call the function `admin_static` or `static`

**Comment by silentsokolov** [comment]
@daniel-ruiz upgrade to 0.3.11 and thanks for PR!

**Comment by daniel-ruiz** [comment]
@silentsokolov thank you for maintaining this awesome project! It was great to contribute and I learned a lot along the way.
