### ISSUE TITLE
Czech localization

### ISSUE THREAD

**Issue by VecnyOptimista** [silentsokolov/django-admin-rangefilter#29]
I would like to add Czech localization. I already prepared new translation file, but I cant push the commit with my branch to your repo.

I only need push access for your repository to be able to create merge request.
Michal.Semenka@Gmail.com

**Comment by silentsokolov** [comment]
We use transifex for localization. Sent invite to [transifex.com](https://www.transifex.com/django-admin-rangefilter/django-admin-rangefilter/)

**Comment by VecnyOptimista** [comment]
Thank you. I sent a join request.

**Comment by mkarajohn** [comment]
@silentsokolov hi, I have made a request too, for a Greek localization. Just letting you know here too, I don't know if you are actively monitoring transifex :sweat_smile: Cheers

**Comment by silentsokolov** [comment]
@mkarajohn done

**Comment by mkarajohn** [comment]
Ok, translation finished! Hoping it gets released soon, We actually need
this in a project! Cheers

**Comment by silentsokolov** [comment]
@mkarajohn thx for a Greek localization, release 0.6.4 is ready!

**Comment by VecnyOptimista** [comment]
Hi, no I am not actively monitoring it. 😁

I hope I still have an access.



Dne so 16. 1. 2021 14:45 uživatel Dimitris Karagiannis <
notifications@github.com> napsal:
