### ISSUE TITLE
Support Spanish translation

### ISSUE THREAD

**Issue by AlexisCaffa** [silentsokolov/django-admin-rangefilter#30]
Write Spanish locales

**Comment by silentsokolov** [comment]
Hello, I don't know Spanish language.
If you are ready to help use [transifex ](https://www.transifex.com/django-admin-rangefilter/django-admin-rangefilter/dashboard/) for localization.

**Comment by AlexisCaffa** [comment]
Late to ask, but anyway: Can I edit the `.po` directly and then run `django-admin compilemessages`?
I just did that in PR https://github.com/silentsokolov/django-admin-rangefilter/pull/31

**Comment by silentsokolov** [comment]
Thx!
