### ISSUE TITLE
Date Widget not displayed

### ISSUE THREAD

**Issue by sandeepharlalka** [silentsokolov/django-admin-rangefilter#35]
ReferenceError: Can't find variable: DateTimeShortcuts on line DateTimeShortcuts.init();

**Comment by silentsokolov** [comment]
Which is the django version and the filter version? How to reproduce?

**Comment by sandeepharlalka** [comment]
Thanks For Your Reply.

Django version is 2.2.1  and Grappelli 2.12.3




On 27-Jul-2019, at 12:10 PM, Dmitriy Sokolov <notifications@github.com<mailto:notifications@github.com>> wrote:


Which is the django version and the filter version? How to reproduce?

**Comment by silentsokolov** [comment]
Grappelli not support but you are welcome to help. PR or anything.
