### ISSUE TITLE
CSS overrides base admin CSS

### ISSUE THREAD

**Issue by niekvanderkooy** [silentsokolov/django-admin-rangefilter#36]
Some of the css provided with the rangefilter (see for example https://github.com/silentsokolov/django-admin-rangefilter/blob/master/rangefilter/templates/rangefilter/date_filter.html#L5-L13) overrides Django admin CSS (see Django admin's base CSS, under `/* FORM BUTTONS */`).

This means that when including extra buttons on an admin page where the rangefilter is also used, their layout is different from pages where the rangefilter is not used.

Is there a reason this CSS is globally overwritten? If not, would it be possible to localize the CSS by adding a custom class?

**Comment by silentsokolov** [comment]
That's a good question. I fix it, thx. 
Please, use master branch or wait a next release.

**Comment by niekvanderkooy** [comment]
Thanks so much!

Just one small detail, your fix in https://github.com/silentsokolov/django-admin-rangefilter/commit/f637b8800d27ebc0aaf80b343549e81b353ae493 only applies to buttons within `.admindatefilter`, but still applies to all `input[type=submit]` etc, since the parent qualifier has not been added there.

I will write a PR now to fix that, so if you could merge that it would be great. (And maybe a quick test - I don't have a test environment set up 😇 )

**Comment by silentsokolov** [comment]
It works fine! Thanks you!

Update to `0.5.1`
