### ISSUE TITLE
Calendar widget not appearing 

### ISSUE THREAD

**Issue by fismerio** [silentsokolov/django-admin-rangefilter#40]
Using Django version 1.11.6 and Python 2.7.15+

Console has:
ReferenceError: DateTimeShortcuts is not defined
jQuery 8
fire
fireWith
updateFunc
fire
fireWith
done
callback
onreadystatechange

**Comment by silentsokolov** [comment]
Test on Python 2.7.16/Django 1.11.6/django-admin-rangefilter 0.5.1/Google chrome latest

[It works fine](http://joxi.ru/L21zEYQhRneO3A)

Please, disable cache (in browser), check custom template.

P.S. The django-admin-rangefilter works only with default admin! No custom theme!
