### ISSUE TITLE
Change date format

### ISSUE THREAD

**Issue by ktotok** [silentsokolov/django-admin-rangefilter#47]
Is there a way to change date format in filter?
By default I have YYYY-mm-dd
i'd like to change it to mm-dd-YYYY

**Comment by silentsokolov** [comment]
We [don't use](https://github.com/silentsokolov/django-admin-rangefilter/blob/master/rangefilter/filter.py#L149) specific the date format. Please, read [django docs](https://docs.djangoproject.com/en/3.0/ref/settings/#date-input-formats).

**Comment by punithbm** [comment]
@ktotok were you able to change the format to mm-dd-YYYY ? - We're also having similar case and trying to override the format to show mm-dd-YYYY. Please let me know if you were able to update that

**Comment by silentsokolov** [comment]
settings.py

```
USE_L10N = False
DATE_INPUT_FORMATS = ['%m-%d-%Y']
```

Result
![1614144636455](https://user-images.githubusercontent.com/398939/108952500-a1f1d400-767a-11eb-970b-a72eecc41820.jpg)
