### ISSUE TITLE
Polish translation

### ISSUE THREAD

**Issue by sqlmiles** [silentsokolov/django-admin-rangefilter#49]
Hi, i finished Polish translation on Transifex platform (thx for invite btw.). Do i need take some action, any PR or something?

**Comment by silentsokolov** [comment]
Hi, I update languages before every release (auto download from Transifex). 

Thanks you for Polish translation!

**Comment by sqlmiles** [comment]
Hello, any chances to include translation on next release? : )

**Comment by silentsokolov** [comment]
@sqlmiles Sorry, I have been waiting Italian guy, but he is disappeared. 

I released new version with Polish translation.
