### ISSUE TITLE
date range icon issue

### ISSUE THREAD

**Issue by portergoh** [silentsokolov/django-admin-rangefilter#5]
Date range from and to "choose a date" icon disappeared once we set
admin.site.disable_action('delete_selected')

or override the following method in our custom admin class

    def get_actions(self, request):
        actions = super(MessageAdmin, self).get_actions(request)
        if request.user.username != 'admin':
            if 'delete_selected' in actions:
                del actions['delete_selected']
        return actions

Tested with Django version 1.10.4

**Comment by silentsokolov** [comment]
Sorry, I do not understand what you mean ... :(

**Comment by portergoh** [comment]
In the text box for from and to date range, there is a calendar picture link where you can choose a date.
That picture link disappeared once you set the following to disable the delete_selected action

admin.site.disable_action('delete_selected')

**Comment by silentsokolov** [comment]
Fixed
