### ISSUE TITLE
Add custom predefined date ranges 

### ISSUE THREAD

**Issue by vekerdyb** [silentsokolov/django-admin-rangefilter#51]
Is it possible to add quick-selections such as "This month", "Last month", "Next month", "This week", ...?

**Comment by wlisesrivas** [comment]
> Is it possible to add quick-selections such as "This month", "Last month", "Next month", "This week", ...?

Django admin default date filter has similar behavior 
![image](https://user-images.githubusercontent.com/1482092/95595406-80bd7d80-0a22-11eb-8645-3e7ff8ebf64e.png)

**Comment by robertpro** [comment]
I would like to mix both, date range + no date + has date, any suggestion @wlisesrivas ?

**Comment by robertpro** [comment]
@vekerdyb This is the code I will use:

```python
class DateRangeListFilter(admin.DateFieldListFilter, DateRangeFilter):
    template = 'admin/filters/date_filter.html'

    def expected_parameters(self):
        params = [self.lookup_kwarg_gte, self.lookup_kwarg_lte]
        if self.field.null:
            params.append(self.lookup_kwarg_isnull)
        return params

    def _make_query_filter(self, request, validated_data):
        query_params = super()._make_query_filter(request, validated_data)
        date_value_gte = validated_data.get(self.lookup_kwarg_gte, None)
        date_value_lte = validated_data.get(self.lookup_kwarg_lte, None)
        date_value_isnull = validated_data.get(self.lookup_kwarg_isnull, None)

        if date_value_isnull is not None and not any([date_value_lte, date_value_gte]):
            query_params[self.lookup_kwarg_isnull] = date_value_isnull

        return query_params

    def _get_form_fields(self):
        fields = super()._get_form_fields()
        fields.update(OrderedDict(
            (
                (self.lookup_kwarg_isnull, forms.BooleanField(
                    label='',
                    localize=True,
                    required=False,
                    widget=forms.HiddenInput,
                )),
            )
        ))
        return fields

```

Result:
![image](https://user-images.githubusercontent.com/8595170/151452768-c4e1dda1-cdbf-463f-a246-6fc20d836e7d.png)

**Comment by jerinpetergeorge** [comment]
Any plans to include this in the package? @silentsokolov

**Comment by Nagendra-babu77** [comment]
> @vekerdyb This is the code I will use:
> 
> ```python
> class DateRangeListFilter(admin.DateFieldListFilter, DateRangeFilter):
>     template = 'admin/filters/date_filter.html'
> 
>     def expected_parameters(self):
>         params = [self.lookup_kwarg_gte, self.lookup_kwarg_lte]
>         if self.field.null:
>             params.append(self.lookup_kwarg_isnull)
>         return params
> 
>     def _make_query_filter(self, request, validated_data):
>         query_params = super()._make_query_filter(request, validated_data)
>         date_value_gte = validated_data.get(self.lookup_kwarg_gte, None)
>         date_value_lte = validated_data.get(self.lookup_kwarg_lte, None)
>         date_value_isnull = validated_data.get(self.lookup_kwarg_isnull, None)
> 
>         if date_value_isnull is not None and not any([date_value_lte, date_value_gte]):
>             query_params[self.lookup_kwarg_isnull] = date_value_isnull
> 
>         return query_params
> 
>     def _get_form_fields(self):
>         fields = super()._get_form_fields()
>         fields.update(OrderedDict(
>             (
>                 (self.lookup_kwarg_isnull, forms.BooleanField(
>                     label='',
>                     localize=True,
>                     required=False,
>                     widget=forms.HiddenInput,
>                 )),
>             )
>         ))
>         return fields
> ```
> 
> Same as [rangefilter/date_filter.html](https://github.com/silentsokolov/django-admin-rangefilter/blob/v0.8.2/rangefilter/templates/rangefilter/date_filter.html), but inserting Django admin/filter.html [here](https://github.com/silentsokolov/django-admin-rangefilter/blob/v0.8.2/rangefilter/templates/rangefilter/date_filter.html#L129=L130), which is this [code](https://github.com/django/django/blob/stable/2.2.x/django/contrib/admin/templates/admin/filter.html#L3-L8) in my case.
> 
> ```
> ...
> <ul>
>     {% for choice in choices %}
>         <li{% if choice.selected %} class="selected"{% endif %}>
>             <a href="{{ choice.query_string|iriencode }}" title="{{ choice.display }}">{{ choice.display }}</a>
>         </li>
>     {% endfor %}
> </ul>
> ...
> ```
> 
> Result: ![image](https://user-images.githubusercontent.com/8595170/151452768-c4e1dda1-cdbf-463f-a246-6fc20d836e7d.png)

Not working for me

**Comment by robertpro** [comment]
@Nagendra-babu77 , there is a bug on my snippet, use this one:

```python
class DateRangeListFilter(admin.DateFieldListFilter, DateRangeFilter):
    template = 'admin/filters/date_range_filter.html'

    def expected_parameters(self):
        params = [self.lookup_kwarg_gte, self.lookup_kwarg_lte]
        if self.field.null:
            params.append(self.lookup_kwarg_isnull)
        return params

    def _make_query_filter(self, request, validated_data):
        query_params = super()._make_query_filter(request, validated_data)
        date_value_gte = validated_data.get(self.lookup_kwarg_gte, None)
        date_value_lte = validated_data.get(self.lookup_kwarg_lte, None)
        date_value_isnull = validated_data.get(self.lookup_kwarg_isnull, None)

        if date_value_isnull is not None and not any([date_value_lte, date_value_gte]):
            query_params[self.lookup_kwarg_isnull] = date_value_isnull

        return query_params

    def _get_form_fields(self):
        fields = super()._get_form_fields()
        if self.field.null:
            fields.update(OrderedDict(
                (
                    (self.lookup_kwarg_isnull, forms.BooleanField(
                        label='',
                        localize=True,
                        required=False,
                        widget=forms.HiddenInput,
                    )),
                )
            ))
        return fields
```

@silentsokolov I have used this code for more than a year, please let me know if it looks good to add it in a PR
