### ISSUE TITLE
Error TemplateDoesNotExist when using rangefilter

### ISSUE THREAD

**Issue by DoMaT** [silentsokolov/django-admin-rangefilter#61]
I installed the plugin and tried using, but get the following error:

Django Version: | 2.1.7
Exception Type: | TemplateDoesNotExist
Exception Value: | rangefilter/date_filter.html
django.template.loaders.filesystem.Loader: /rangefilter/date_filter.html (Source does not exist)

Any idea why?

**Comment by silentsokolov** [comment]
Please, full stacktrace

**Comment by vladjkeee13** [comment]
> I installed the plugin and tried using, but get the following error:
> 
> Django Version: | 2.1.7
> Exception Type: | TemplateDoesNotExist
> Exception Value: | rangefilter/date_filter.html
> django.template.loaders.filesystem.Loader: /rangefilter/date_filter.html (Source does not exist)
> 
> Any idea why?

I think you just forgot to add app to your settings.

**Comment by silentsokolov** [comment]
Reopen if needed

**Comment by DoMaT** [comment]
Works fine, sorry for confusion!
