### ISSUE TITLE
Search does not occur after pressing the "search" button

### ISSUE THREAD

**Issue by kebrick** [silentsokolov/django-admin-rangefilter#64]
Django version 3.2

**Comment by silentsokolov** [comment]
Is default admin ui?

**Comment by kebrick** [comment]
No I'm using jazzmin ui

**Comment by silentsokolov** [comment]
We support only the default admin ui ((
You can override templates for your ui if needed.

Welcome PR))

**Comment by kebrick** [comment]
Может кому поможет, js скрипт пытается вытащить данные из формы под id="{{ choices.0.system_name }}-form". 
Но Jazzmin UI рендерит форму под id="changelist-search"
Как это правильно исправить я пока не знаю.
[Пример формы test.zip](https://github.com/silentsokolov/django-admin-rangefilter/files/6472588/test.zip)

**Comment by mudsut4ke** [comment]
@kebrick ,I also found this issue with jazzmin ui
Do you have a solution to this issue ?

**Comment by kebrick** [comment]
> @kebrick , я тоже обнаружил эту проблему с jazzmin ui.
> У вас есть решение этой проблемы?
This is a bad decision on my part, but I had to take the source codes and change the "date_filter.html" template. I removed
  the whole block (<div class = "admindatefilter">) and added "{{spec.form}}" instead
[date_filter.zip](https://github.com/silentsokolov/django-admin-rangefilter/files/6662315/date_filter.zip)

**Comment by mudsut4ke** [comment]
@kebrick , Thank you
