### ISSUE TITLE
Range Filter by two fields

### ISSUE THREAD

**Issue by W0rtX** [silentsokolov/django-admin-rangefilter#69]
Hello, thank you for your code!

Could you tell, how i can range filter by two fields?

My model have fields: created and finished.
If i add filter into list filter in django-admin, i receive next url: ?q=&created_at__range__gte_0=2021-10-01&created_at__range__gte_1=22%3A00&created_at__range__lte_0=2021-10-03&created_at__range__lte_1=8%3A00

But i need next url: ?q=&created_at__range__gte_0=2021-10-01&created_at__range__gte_1=22%3A00&finished_at__range__lte_0=2021-10-03&finished_at__range__lte_1=8%3A00

Is there a simple way to do this? 
Thanks

**Comment by silentsokolov** [comment]
Show your ModelAdmin

**Comment by W0rtX** [comment]
> from rangefilter.filter import AdminSplitDateTime, DateTimeRangeFilter as OriginalDateTimeRangeFilter
> class TaskAdmin(admin.ModelAdmin):
>   list_display = (
>     'created_at',
>     'finished_at',
>   )
>   list_filter = (
>     ('created_at', OriginalDateTimeRangeFilter),
>   )

**Comment by silentsokolov** [comment]
```python
list_filter = (
    ('created_at', OriginalDateTimeRangeFilter),
    ('finished_at', OriginalDateTimeRangeFilter),
)
```

Does it not work?

**Comment by W0rtX** [comment]
This works, but two filters are created: by creation date and by finished date, and I need to make sure that these two fields are combined in one filter: DateFrom is compared with the creation date, and DateTo with the finished date

**Comment by silentsokolov** [comment]
Please check version from the master branch
