### ISSUE TITLE
Invalid Calendar position with right to left locals

### ISSUE THREAD

**Issue by YDA93** [silentsokolov/django-admin-rangefilter#72]
Calendar is always hidden when I am browsing in Arabic local (Right to left language)

![Screen Shot 2022-01-29 at 7 02 46 PM](https://user-images.githubusercontent.com/70075736/151667907-bf71bed5-485a-4ad2-87f9-700ac44a9c0a.png)

**Comment by silentsokolov** [comment]
Duplicate #17
