### ISSUE TITLE
Use of `admin_static` causes `validate_templates`  fails

### ISSUE THREAD

**Issue by amrishparmar** [silentsokolov/django-admin-rangefilter#78]
When I attempt to run the ~built-in~ Django management command `validate_templates`, this library triggers the following error
```
/usr/local/lib/python3.10/site-packages/rangefilter/templates/rangefilter/date_filter_1_8.html: TemplateSyntaxError 'admin_static' is not a registered tag library.
```

Python version: 3.10.4
Django version: 4.0.4

Though I have only tested this on Django 4, this same error will likely be present in all versions of Django >= 3.0 as that's [when the deprecated feature was removed](https://docs.djangoproject.com/en/4.0/releases/3.0/#features-removed-in-3-0)

**Comment by silentsokolov** [comment]
`validate_templates` this is not official command.

We use different templates in our code for the different the django versions. `date_filter_1_8.html` - template for <= 1.8.

I think about how to resolve.
