### ISSUE TITLE
Error 500 when filtering by date range and foreign key field

### ISSUE THREAD

**Issue by SrLeo-projects** [silentsokolov/django-admin-rangefilter#81]
I have 2 models in my project, Order and Ticket
Tickets are created when an order is paid so they have a one to many relation.
On Django admin, I need to filter tickets by order__branch and date range, but it doesn't work.

Is there a way to avoid this?

these are the parameters of the url and the message I get
?order__branch__id__exact=5&created_at__range__gte=01%2F08%2F2022&created_at__range__lte=10%2F08%2F2022

![image](https://user-images.githubusercontent.com/85948792/184041424-e3dc9f31-8a0f-4d54-85f1-92ef3b3f8ee9.png)

**Comment by silentsokolov** [comment]
This is hard to debug. Can you add a debug message or anything else?

**Comment by SrLeo-projects** [comment]
I have no messages in logs but I think its solved.
My filter list was like this: order, order__branch and the created_at with the rangefilter
So deleting 'order' from the list was the solution. I dont know why but I'll leave it here.
Thanks for your response

**Comment by silentsokolov** [comment]
Close. Reopen if needed.
