### ISSUE TITLE
Filter for calculated fields

### ISSUE THREAD

**Issue by KaktusOnFire** [silentsokolov/django-admin-rangefilter#86]
Any solution to make custom filter for calculated Admin fields?

Example:

```python
@admin.register(Test)
class TestAdmin(model.ModelAdmin):
    list_display = ("sale_date", "another_field")
    list_filter = (
        ....
    )

    def sale_date(self, obj):     #Field for filter
        result: datetime = do_some_logic()
        return result
```

**Comment by silentsokolov** [comment]
Hmm ... I don't know a good solution, but if a query speed does not matter. You can create manager like

```python
class FooBarManager(models.Manager):
    def sale_date(self, start_dt, end_dt):
       do_some_logic()
       return queryset
```

And then overwrite [method queryset](https://github.com/silentsokolov/django-admin-rangefilter/blob/3641145dbeba117fafc531b9e7a301cf6114375b/rangefilter/filters.py#L145).
