### ISSUE TITLE
List items have a second date selection widget when list_editable

### ISSUE THREAD

**Issue by max-pfeiffer** [silentsokolov/django-admin-rangefilter#9]
Using Django 1.11.5, to reproduce:

list_display = ('charfield', 'date_field') 
list_editable = ('date_field',)
list_filter = (('date_field', DateRangeFilter),)

See Screenshot.

![screen shot 2017-09-07 at 16 53 08](https://user-images.githubusercontent.com/13573675/30169602-261a2954-93ed-11e7-9cac-becabe09fac3.png)

**Comment by silentsokolov** [comment]
This is due to multiple load `admin/DateTimeShortcuts.js` on page. I spent many hours, but did not figure out how to fix it ((

**Comment by silentsokolov** [comment]
Good solution, but not works with two filtres.

Test on:
```python
@admin.register(Post)
class PostAdmin(admin.ModelAdmin):
    list_display = ('name', 'created_at')
    list_editable = ('created_at',)
    list_filter = (
        'name', ('created_at', DateRangeFilter), ('updated_at', DateRangeFilter),
    )
```
